name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checagem do codigo
      - name: Checkout do codigo
        uses: actions/checkout@v4

      # Etapa 2: Configurar o Node.js
      - name: Setando o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Etapa 3: Instalar dependências
      - name: Instalando Dependencias
        run: npm install

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do código
      - name: Checkou do codigo
        uses: actions/checkout@v4

      # Etapa 2: Configurar o Docker
      - name: Configurando o Docker
        uses: docker/setup-buildx-action@v2

      # Etapa 3: Fazer build da imagem Docker
      - name: Build da imagem Docker
        run: docker build -t todolist .

      # Etapa 4: Push da imagem para o Docker Hub ou registry
      - name: Log in no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push eliineto/todolist:latest
