name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout o código do repositório
      - name: Checkout Code
        uses: actions/checkout@v4

      # Etapa 2: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Etapa 3: Instalar dependências
      - name: Install Dependencies
        run: npm install

      # Etapa 4: Lint (opcional, se configurado)
      - name: Lint Code
        run: npm run lint

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout o código
      - name: Checkout Code
        uses: actions/checkout@v4

      # Etapa 2: Configurar o Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Etapa 3: Fazer build da imagem Docker
      - name: Build Docker Image
        run: docker build -t your-app-name .

      # Etapa 4: Push da imagem para o Docker Hub ou registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push eliineto/todolist:latest
